### ISSUE TITLE
mqtt-workers-binance-futures-account 38行 

### ISSUE THREAD

**Issue by dazi005** [kuuy/taoniu-go#1]
MQTT_TOPICS_ACCOUNT  这个常量config.go 没看到定义,可否提交一下,老大,加个好友留个V,可以?

**Comment by kuuy** [comment]
麻烦拉下最新的代码，有问题直接在这里提交就可以了。

**Comment by dazi005** [comment]
收到 ,
<img width="516" alt="image" src="https://github.com/kuuy/taoniu-go/assets/5207054/e60a6979-0d96-420b-b3d4-15e7fcdd30ad">
